### ISSUE TITLE
sending email blank display

### ISSUE THREAD

**Issue by fanerobinson** [fanerobinson/PSA#17]
when you send an email the added post is blank until you close and reopen the ticket, appears to just be cosmetic

**Comment by fanerobinson** [comment]
![image](https://cloud.githubusercontent.com/assets/23490104/21970587/a9418048-dbe2-11e6-8405-fbb0e45608aa.png)

**Comment by huzzamo** [comment]
Fixed it. Weird issue caused by a line break getting appended to a reference ID.

________________________________

**Comment by fanerobinson** [comment]
not resolved, just happened again :(

![image](https://cloud.githubusercontent.com/assets/23490104/22006325/2a55b542-dca5-11e6-980d-208d0c83e79c.png)

**Comment by huzzamo** [comment]
Hi Fane,


Just trying to work out the exact issue as I tried again with the same text and works fine: http://psaprod.biz-lynx.com.au/Ticketing/EditViewTicket.php?ticketID=12345678&mode=edit (Keep this open as that way can check on bugs)


- Is the 1st email you sent today and if not is this happening all the time or sometimes?

- What browser your using?


Thanks,



Husein

________________________________

**Comment by fanerobinson** [comment]
Every single time, the email sent is fine, it’s the display that is blank - chrome


[BIZ-LYNX Technology logo]

Fane Robinson

Systems Engineer
BIZ-LYNX Technology Pty Ltd





Phone

(+618) 6263-9400

Fax

(+618) 6263-9420

Email

team@biz-lynx.com.au<mailto:team@biz-lynx.com.au>


www.biz-lynx.com.au <http://www.biz-lynx.com.au/>


Trading Hours

WST

09:00 - 17:00 Monday - Friday

EST

11:00 - 19:00 Monday - Friday

Other

By Appointment





P Please consider the environment before printing this email, be green, read from the screen!
